### ISSUE TITLE
Question: Should groovyfx build.gradle have comment about using java 1.7 instead of 1.6?

### ISSUE THREAD

**Issue by faroe228** [groovyfx-project/groovyfx-project.github.com#1]
Q: Should build.gradle have comment about using java 1.7 instead of 1.6 for certain usage scenarios?

I recently gave grooyfx a try and it worked perfectly on my MacBook Air ( OS X 10.7 Lion ) with java version "1.7.0_17" but on my Windows machine I had to change 

sourceCompatibility = 1.6
targetCompatibility = 1.6
to
sourceCompatibility = 1.7
targetCompatibility = 1.7

in build.gradle.

Now that JavaFX comes bundled with Java 7, I wonder if most end users of JavaFX 2 will be Java 7 users instead of Java 6 users and using source and target computability values of 1.7 instead of 1.6 would be a better general default value to use?

**Comment by russel** [comment]
This issue has been overtaken by events and updates, so I am closing it.
